[tool.poetry]
name = "requestium"
version = "0.5.0"
description = ""
authors = ["Joaquin Alori <joaquin@tryolabs.com>"]
readme = "README.md"
license = "BSD-3-Clause"

[tool.poetry.dependencies]
python = ">=3.9,<3.14"
parsel = "1.9.1"
requests = "2.32.3"
selenium = "4.27.1"
tldextract = "5.1.3"

[tool.poetry.group.dev.dependencies]
bandit = "1.8.0"
coverage = "7.6.10"
pytest = "8.3.4"
ruff = "0.9.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
