name: Pytest

on:
  push:
    paths:
      - "**.py"
      - .github/workflows/pytest.yml
      - pyproject.toml
  pull_request:
    paths:
      - "**.py"
      - pyproject.toml
  workflow_dispatch:

jobs:
  pytest:
    strategy:
      fail-fast: false
      matrix:
        os:
          # - "ubuntu-latest" # doesn't work without headless
          - "windows-latest"
          - "macos-latest"
        python-version:
          - "3.12"
          - "3.11"
          - "3.10"
          - "3.9"
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install uv and create venv
        run: |
          pip install -U pip uv
          uv venv

      - name: Enable macOS/Linux venv
        if: runner.os != 'Windows'
        run: |
          source .venv/bin/activate
          echo $PATH >> $GITHUB_PATH

      - name: Enable Windows venv
        if: runner.os == 'Windows'
        run: |
          .venv\Scripts\activate
          echo $env:path >> $ENV:GITHUB_PATH

      - name: Install dependencies
        run: |
          uv pip install -r requirements.txt
          uv pip install -e . pytest pytest-cov

      - name: Test with pytest
        run: |
          pytest --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
